version: '3'

services:
  application:
    build:  .
    container_name: application
    entrypoint: .docker/entrypoint.sh
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/app
  database:
    image: postgres
    container_name: database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=database