name: Check Main Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  check-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Check if PR is from develop
        if: ${{ github.event.pull_request.base.ref != 'develop' }}
        run: |
          echo "Erro: Esta pull request sรณ pode ser feita da branch develop para a main."
          exit 1
